name: Import Word templates

on:
  push:
    branches:
      - develop
    paths:
      - 'meta/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
    - name: Import changes in metadata templates
      run: python scripts/import-word-templates.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: import updated Word templates
        title: Changes from updated Word templates
        body: Import source changes for translation from the latest Word templates.
        branch: import-word-templates
        token: ${{ secrets.token }}
